version: "3"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3303:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./.docker/mysql/database/init:/docker-entrypoint-initdb.d
            - database:/var/lib/mysql
        tty: true
        restart: unless-stopped
        networks:
            laravel:
    nginx:
        build:
            context: ./
            dockerfile: ./.docker/nginx/Dockerfile
            args:
                - DOMAIN=${APP_URL:-localhost}
        image: aadilagwan/nginx:1.0
        restart: unless-stopped
        container_name: nginx
        tty: true
        ports:
            - "80:80"
            - "443:443"

        networks:
            laravel:
                ipv4_address: 192.168.30.30
    php:
        build:
            context: ./
            dockerfile: ./.docker/php74/Dockerfile
        container_name: php
        image: aadilagwan/php:1.0
        volumes:
            - ./:/var/www/html
        ports:
            - "8001:9000"
        depends_on:
            - mysql
            - nginx
        networks:
            laravel:

volumes:
    database:

networks:
  laravel:
    ipam:
      driver: default
      config:
        - subnet: "192.168.30.0/24"
